"""F4.2 — train the four AcousticProbe heads.

Inputs:
  --manifest <path>   CSV file with columns:
                        path, voice_naturalness, spectral_consistency,
                        temporal_patterns, artifact_detection
                      Each label is a float in [0, 1]. The audio at `path`
                      is loaded, resampled to 16 kHz, and converted to a
                      75-D feature vector via `acoustic_features.extract`.
  --output <path>     Where to write the bundled `aasist_heads.pt`.
  --epochs <int>      Default 50.
  --val-split <float> Default 0.15.
  --report-thresholds When set, the script also computes per-axis EER
                      thresholds on the validation set and prints them so
                      they can be folded into `Settings.*_threshold`.

Methodology (see `docs/paper/sub_classifier.md` §4):

  - Each axis is treated as an independent regression problem; we train
    four small MLPs (75 → 64 → 1) with sigmoid output and binary
    cross-entropy loss against the (continuous) label.
  - `--manifest` rows can be hand-annotated or generated by
    `build_proxy_labels.py` from raw acoustic metrics. The paper
    explicitly distinguishes the two; published numbers always use
    hand-annotated subsets.
  - Heads are saved as a dict-of-state-dicts so the runtime
    AcousticProbe can load them without instantiating the full
    `_MLPHead` class until the file is present.

Real datasets to use:
  - VoxCeleb1 + ASVspoof2019 LA + bundled F5-TTS / XTTS clones.
  - 70 / 15 / 15 train / val / test split.
  - Annotation schema in `docs/paper/sub_classifier_dataset.md`.

Without a real dataset you can still smoke-test the pipeline:

    cd backend
    .venv/bin/python scripts/train_sub_classifier.py \\
        --manifest tests/fixtures/sub_classifier_demo_manifest.csv \\
        --output models/aasist_heads.pt \\
        --epochs 5

The runtime detects the presence of `aasist_heads.pt` and switches
AcousticProbe to trained-head mode automatically (see
`backend/app/services/sub_classifier.py`).
"""

from __future__ import annotations

import argparse
import csv
import logging
import sys
import wave
from io import BytesIO
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn

# Allow running from the backend/ root.
THIS_DIR = Path(__file__).resolve().parent
BACKEND_ROOT = THIS_DIR.parent
sys.path.insert(0, str(BACKEND_ROOT))

from app.services.acoustic_features import FEATURE_DIM, extract  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger("train_sub_classifier")


AXIS_NAMES = (
    "voice_naturalness",
    "spectral_consistency",
    "temporal_patterns",
    "artifact_detection",
)


def load_wav(path: Path) -> tuple[np.ndarray, int]:
    """Read a WAV. 16-bit mono only — same constraint as AudioService."""
    with wave.open(str(path), "rb") as handle:
        sr = handle.getframerate()
        n = handle.getnframes()
        sw = handle.getsampwidth()
        ch = handle.getnchannels()
        frames = handle.readframes(n)
    if sw != 2:
        raise ValueError(f"{path}: expected 16-bit PCM (got {sw * 8}-bit)")
    samples = np.frombuffer(frames, dtype=np.int16).astype(np.float32) / 32768.0
    if ch == 2:
        samples = samples.reshape(-1, 2).mean(axis=1)
    return samples, sr


def load_manifest(manifest_path: Path) -> tuple[np.ndarray, np.ndarray]:
    """Walk the manifest, extract features, return (X, Y) numpy arrays."""
    rows = list(csv.DictReader(manifest_path.open()))
    X = np.zeros((len(rows), FEATURE_DIM), dtype=np.float32)
    Y = np.zeros((len(rows), len(AXIS_NAMES)), dtype=np.float32)
    for i, row in enumerate(rows):
        wav_path = Path(row["path"])
        if not wav_path.is_absolute():
            wav_path = manifest_path.parent / wav_path
        try:
            samples, sr = load_wav(wav_path)
        except Exception as exc:
            logger.warning("Skipping %s: %s", wav_path, exc)
            continue
        features = extract(samples.tolist(), sample_rate=sr)
        X[i] = features.vector
        for j, axis in enumerate(AXIS_NAMES):
            Y[i, j] = float(row[axis])
        if i % 100 == 0 and i > 0:
            logger.info("Loaded %d / %d clips", i, len(rows))
    logger.info("Loaded manifest: %d clips × %d features", len(rows), FEATURE_DIM)
    return X, Y


class MLPHead(nn.Module):
    def __init__(self, input_dim: int, hidden: int = 64):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, hidden)
        self.fc2 = nn.Linear(hidden, 1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.fc2(torch.relu(self.fc1(x)))


def train_axis(
    name: str, X_train: np.ndarray, y_train: np.ndarray, X_val: np.ndarray, y_val: np.ndarray,
    epochs: int, batch_size: int = 64, lr: float = 1e-3,
) -> tuple[MLPHead, dict[str, float]]:
    head = MLPHead(FEATURE_DIM)
    optim = torch.optim.Adam(head.parameters(), lr=lr)
    bce = nn.BCEWithLogitsLoss()
    Xt = torch.from_numpy(X_train)
    yt = torch.from_numpy(y_train).unsqueeze(-1)
    Xv = torch.from_numpy(X_val)
    yv = torch.from_numpy(y_val).unsqueeze(-1)

    best_val_loss = float("inf")
    for epoch in range(epochs):
        head.train()
        perm = torch.randperm(Xt.shape[0])
        epoch_loss = 0.0
        for start in range(0, Xt.shape[0], batch_size):
            idx = perm[start : start + batch_size]
            pred = head(Xt[idx])
            loss = bce(pred, yt[idx])
            optim.zero_grad()
            loss.backward()
            optim.step()
            epoch_loss += float(loss.item()) * idx.numel()
        epoch_loss /= max(1, Xt.shape[0])
        with torch.no_grad():
            head.eval()
            val_pred = head(Xv)
            val_loss = float(bce(val_pred, yv).item())
        if val_loss < best_val_loss:
            best_val_loss = val_loss
        if (epoch + 1) % max(1, epochs // 10) == 0:
            logger.info("[%s] epoch %2d  train=%.4f  val=%.4f", name, epoch + 1, epoch_loss, val_loss)
    return head, {"final_val_loss": best_val_loss}


def report_per_concept_eer(head: MLPHead, X_val: np.ndarray, y_val: np.ndarray) -> float:
    """Compute the EER threshold on the validation set. Used to suggest
    the per-concept thresholds in Settings (F4.4)."""
    head.eval()
    with torch.no_grad():
        scores = torch.sigmoid(head(torch.from_numpy(X_val))).squeeze(-1).numpy()
    # Treat axis label > 0.5 as "positive" for the EER calculation. The
    # reported threshold is the score s* where FAR(s*) ≈ FRR(s*).
    labels = (y_val > 0.5).astype(np.int32)
    if labels.sum() == 0 or labels.sum() == labels.size:
        return 0.5  # degenerate manifest
    best_t = 0.5
    best_diff = float("inf")
    for t in np.linspace(0.01, 0.99, 99):
        far = float(((scores >= t) & (labels == 0)).sum() / max(1, (labels == 0).sum()))
        frr = float(((scores < t) & (labels == 1)).sum() / max(1, (labels == 1).sum()))
        if abs(far - frr) < best_diff:
            best_diff = abs(far - frr)
            best_t = t
    return float(best_t)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--val-split", type=float, default=0.15)
    parser.add_argument("--report-thresholds", action="store_true")
    args = parser.parse_args()

    X, Y = load_manifest(args.manifest)
    if X.shape[0] == 0:
        logger.error("No usable clips in %s", args.manifest)
        return 2

    rng = np.random.default_rng(seed=42)
    perm = rng.permutation(X.shape[0])
    X = X[perm]
    Y = Y[perm]
    n_val = max(1, int(X.shape[0] * args.val_split))
    X_train, X_val = X[n_val:], X[:n_val]
    Y_train, Y_val = Y[n_val:], Y[:n_val]
    logger.info("Train %d  Val %d", X_train.shape[0], X_val.shape[0])

    state_out = {}
    suggested_thresholds = {}
    for j, name in enumerate(AXIS_NAMES):
        head, _ = train_axis(name, X_train, Y_train[:, j], X_val, Y_val[:, j], epochs=args.epochs)
        # Persist as a dict-of-state-dicts so the runtime _load_head can
        # consume it without depending on this script's module path.
        state_out[name] = {
            "fc1": head.fc1.state_dict(),
            "fc2": head.fc2.state_dict(),
        }
        if args.report_thresholds:
            suggested_thresholds[name] = report_per_concept_eer(head, X_val, Y_val[:, j])

    args.output.parent.mkdir(parents=True, exist_ok=True)
    torch.save(state_out, args.output)
    logger.info("Wrote heads → %s", args.output)

    if args.report_thresholds:
        logger.info("Suggested per-concept thresholds (paste into Settings):")
        for name, t in suggested_thresholds.items():
            logger.info("  %s_threshold = %.3f", name, t)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
